### PR TITLE
Enhancement node8 installation script #41

### LINKED ISSUE #41: Automatic installation of appropriate node 8
**What?**
Write a script to install appropriate node 8 nightly automatically using npm script.

**How?**
```bash
npm run install-node8
```

### PR DESCRIPTION
**Pull request by nidin**
Added a node script to install node-v8 on linux, mac and windows.
closes #41

### CODE REVIEW

**Comment by winksaville** [comment]
I'd be cautious of using the latest nightly build. As it could be broken, I suggest testing first and then using a particular version for a period of time. Also behavior could change so making reproducing problems difficult.

**Comment by winksaville** [comment]
I suggest storing the entire url in a file, instead of what you've done. That way it could be pointed to a build else where. The simplest might be to use a json formatted file maybe something like:
```
{
  "option": {
     "node-v8-nightly-build": {
      "os": {
         "linux": {
            "url": "http://xxxx"
         },
         "windows10": {
            "url": "http://xxxx"
         },
         ...
      }
   }
}
```

**Comment by nidin** [comment]
I was also thinking the same thing. Mac node-v8 is broken so i will try to find out working version and make it as default one. I wouldn't spent more time on this setup since its a temporary workaround and this script will be obsolete once node-v8 released

**Comment by nidin** [comment]
I will do so.

**Comment by nidin** [comment]
Change approve to change request.

**Comment by nidin** [comment]
Included in Jest testing framework pull request

**Pull request closed without merging**
