### PR TITLE
Fixed a couple of dev issues on windows

### PR DESCRIPTION
**Pull request by dcodeIO**
install-node-v8 now also searches for 7z in the default install location and, within package.json, a wrapper is used to spawn node-v8 for 'cmd' compatibility.

### CODE REVIEW

**Comment by dcodeIO** [comment]
From the logs I am not exactly sure why the build is failing. The PR actually didn't touch the download portion of install-node-v8 and it is working fine for me locally. Hmm...

**Comment by dcodeIO** [comment]
Found it: It appears that there is no windows build (yet) at https://nodejs.org/download/nightly/v8.0.0-nightly20170508ea1b8a5cbc/

**Comment by MaxGraey** [comment]
We should split node-v8 version for this case, because for mac only this 20170508ea1b8a5cbc snapshot workable in current time.

**Comment by nidin** [comment]
That's a known issue. JSON file is updating prior to binary upload. May be take second last nightly build from the list.

**Pull request merged**
