### PR TITLE
Improve arrays. Add NaN / Infinity constants

### PR DESCRIPTION
**Pull request by MaxGraey**
- Improve array;
- add NaN and Infinity for float32;
- add isNaN() and isFinite() for float32;

### CODE REVIEW

**Comment by MaxGraey** [comment]
Hm, It seems travis fail on addTwo tests

**Comment by nidin** [comment]
Let me checkout your branch and test manually

**Comment by MaxGraey** [comment]
Problem with Assertion failed still presents. array.tbs compiles and executed normally, but others test failed

**Comment by MaxGraey** [comment]
I think about it as well. And the best approach it should be like this:
```ts
declare type Float32Array   = Array< float32 >
```

But there is no possibility to compile it

**Comment by MaxGraey** [comment]
I found the problem. Had to do the Array is non-exported

**Pull request merged**
