### PR TITLE
Move stdlib to common

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by winksaville** [comment]
You there to it as stdlib, should it be in a dir called stdlib?

**Comment by MaxGraey** [comment]
It's need to move forward and exclude runtime.js and wrapper.js from library.

**Comment by winksaville** [comment]
I corrected my previous statement, so maybe you misunderstood. I'm suggesting rather than being called `common` the directory should be called `stdlib`?

**Comment by nidin** [comment]
@winksaville we will refactor stdlib later, now "common" contains common library source code for asm.js and WASM.

**Comment by winksaville** [comment]
SG

**Pull request merged**
